export interface caseReport_NC {
  document_no: string,
  site_id: number,
  department_id: number,
  department: string,
  client_id: number,
  client: string,
  vehicle_id_head: number,
  vehicle_head: string,
  vehicle_id_tail: number,
  vehicle_tail: string,
  vehicle_truckno: string,
  origin_id: number,
  reporter:string,
  priority: string,
  site: string,
  driver_role: string,
  driver: string,
  driver_role_id: number,
  driver_id: string,
  incident_cause_id: number,
  reporter_id: number,
  record_date: string,
  incident_date: string,
  case_location: string,
  incident_cause: string,
  description: string,
  destination: string,
  case_details: string,
  estimated_cost: number,
  actual_price: number,
  attachments: string,
  casestatus: string,
  products: [
    {
      product_id: number,
      product_name: string,
      amount: number,
      unit: string
    }
  ],
 docs: [
    {
      warning_doc: string,
      warning_doc_no: string,
      warning_doc_remark: string,
      debt_doc: string,
      debt_doc_no: string,
      debt_doc_remark: string,
      customer_invoice: string,
      customer_invoice_no: string,
      customer_invoice_remark: string,
      Insurance_claim_doc: string,
      Insurance_claim_doc_no: string,
      Insurance_claim_doc_remark: string,
      writeoff_doc: string,
      writeoff_doc_remark: string,
      damage_payment: string,
      damage_payment_no: string,
      damage_payment_remark: string,
      account_attachment_no: string,
      account_attachment_remark: string
    }
  ]
}

export interface caseReport_AC {
    site_id: number,
    case_id: string,
    department_id: number,
    client_id: number,
    origin_id: number,
    reporter_id: number,
    reporter_name: string,
    record_datetime: string,
    incident_datetime: string,
    province_name_th: string,
    province_name_en: string,
    district_name_th: string,
    district_name_en: string,
    sub_district_name_th: string,
    sub_district_name_en: string,
    province_id: number,
    district_id: number,
    sub_district_id: number,
    case_location: string,
    police_station_area: string,
    vehicle_id_head: number,
    vehicle_id_tail: number,
    vehicle_truckno: string,
    driver_role_id: number,
    driver_id: string,
    case_details: string,
    alcohol_test: string,
    drug_test: string,
    truck_damage: string,
    truck_damage_details: string,
    product_damage: string,
    product_damage_details: string,
    injured_not_hospitalized: number,
    injured_hospitalized: number,
    fatalities: number,
    injury_description: string,
    other_party_full_name: string,
    other_party_vehicle_plate: string,
    other_party_company_name: string,
    other_party_phone: string,
    other_party_insurance_name: string,
    other_party_claim_no: string,
    claim_officer_full_name: string,
    claim_officer_phone: string,
    estimated_goods_damage_value: number,
    estimated_vehicle_damage_value: number,
    actual_goods_damage_value: number,
    actual_vehicle_damage_value: number,
    attachments: string,
    casestatus: string,
    priority: string,
    destination: string,
    alcohol_test_result: number,
    drug_test_result: string,
    accident_case_id: number,
    document_no_ac: string,
    docs: [
    {
      warning_doc: string,
      warning_doc_no: string,
      warning_doc_remark: string,
      debt_doc: string,
      debt_doc_no: string,
      debt_doc_remark: string,
      customer_invoice: string,
      customer_invoice_no: string,
      customer_invoice_remark: string,
      Insurance_claim_doc: string,
      Insurance_claim_doc_no: string,
      Insurance_claim_doc_remark: string,
      writeoff_doc: string,
      writeoff_doc_remark: string,
      damage_payment: string,
      damage_payment_no: string,
      damage_payment_remark: string,
      account_attachment_no: string,
      account_attachment_remark: string
    }
  ]
}

export interface investigate_NC {
 root_cause_analysis: string,
  claim_type: string,
  insurance_claim: number,
  product_resellable: number,
  remaining_damage_cost: number,
  driver_cost: number,
  company_cost: number,
  corrective_actions: [
    {
      id: number,
      corrective_action: string,
      pic_contract: string,
      plan_date: string,
      action_completed_date: string
    }
  ]
}